blank_issues_enabled: false
contact_links:
  - name: Technical Discussion
    url: https://forum.pretendo.network/c/technical-discussion
    about: Please use our forum for general technical discussions.
