name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["feature", "awaiting-approval"]
assignees: []
body:
  - type: checkboxes
    attributes:
      label: Checked Existing
      description: Ensure you have checked the existing issues, both open and closed, for duplicate issues.
      options:
        - label: I have checked the repository for duplicate issues.
          required: true
  - type: textarea
    id: what-feature
    attributes:
      label: What feature do you want to see added?
    validations:
      required: true
  - type: textarea
    id: why-feature
    attributes:
      label: Why do you want to have this feature?
      placeholder: A new button!
    validations:
      required: true
  - type: textarea
    id: other-details
    attributes:
      label: Any other details to share? (OPTIONAL)
    validations:
      required: false