name: Question
description: Ask a general question
title: "[Question]: "
labels: ["question"]
assignees: []
body:
  - type: checkboxes
    attributes:
      label: Checked Existing
      description: Ensure you have checked the existing issues, both open and closed, for duplicate issues.
      options:
        - label: I have checked the repository for duplicate issues.
          required: true
  - type: textarea
    id: question
    attributes:
      label: What would you like to know?
    validations:
      required: true